### ISSUE TITLE
python.EXE is v3.5.1, which is not supported by gyp.

### ISSUE THREAD

**Issue by michaelswanson25** [datatypevoid/vulgar#10]
I run: npm install -g vulgar-cli generator-vulgar

And I get this error message:

C:\Users\u926923\AppData\Roaming\npm\node_modules\vulgar-cli\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\u926923\AppData\Local\Programs\Python\Python35\python.EXE" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\u926923\AppData\Roaming\npm\node_modules\vulgar-cli\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by Codenator81** [comment]
I am give app on windows for this problems. Delete your new Python and install needed for Gyp and not forget change PATH

**Comment by datatypevoid** [comment]
@Codenator81 is correct. Installing `Python x86` version between `2.5` and `3.0` on Windows should fix this problem. Let me know it this works for you.

**Comment by michaelswanson25** [comment]
Thanks.  I did this.  Now I have a new error with node-gyp.  I'm behind a corporate web proxy that messed up the cert chain.  I'm setting NODE_TLS_REJECT_UNAUTHORIZED=0 but it doesn't seem to work:

$ npm install

```

> node-zopfli@1.4.0 install C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.4.3 (node-v46 ABI) (falling back to source compile with node-gyp)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\u926923\\Desktop\\Dev\\Sandbox\\vulgarTest\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Documents and Settings\\u926923\\Desktop\\Dev\\Sandbox\\vulgarTest\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\Documents and Settings\\u926923\\Desktop\\Dev\\Sandbox\\vulgarTest\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Documents and Settings\\u926923\\Desktop\\Dev\\Sandbox\\vulgarTest\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Documents and Settings\u926923\Desktop\Dev\Sandbox\vulgarTest\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
```

**Comment by datatypevoid** [comment]
This is definitely something to do with your `node-gyp` installation. Have you have any luck in solving the issue?

**Comment by michaelswanson25** [comment]
You're right.  I breezed through everything on a box that was at home.  It's this corporate MitM web proxy that is killing me.

**Comment by datatypevoid** [comment]
Alright cool,  glad to hear everything worked out. 

On a side note, if you want to stay ahead of the curve,  the development branch is almost ready for release and has the entire backend refactored with TypeScript. Feel free to come join us on Slack if you need anything or just want to chat about Web develop.
