### ISSUE TITLE
when can we use ng-router 3.0

### ISSUE THREAD

**Issue by mathjoy** [datatypevoid/vulgar#15]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)
- *_I'm submitting a ... *_
  
  [ ] bug report
  
  [ x] feature request
  
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
- **What is the current behavior?**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- https://plnkr.co, https://codepen.io, or similar.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by datatypevoid** [comment]
The development branch already supports the new router as well as the rest of the things released since beta ended. You can check that out at https://github.com/datatypevoid/vulgar/tree/development

Let me know if I can help with anything else, and feel free to join our Slack for any other questions.
