### ISSUE TITLE
How to include bower plugin?

### ISSUE THREAD

**Issue by sieryuu** [datatypevoid/vulgar#16]
I gonna use bootstrap template which I can get from bower_component, how do I include it in my project?

**Comment by datatypevoid** [comment]
Do you have to use bower specifically? The pack doesn't use bower because it's generally unneeded afaik with npm being available to the entire stack now. I can help you install it if really have to have it, but you'll have to join our Slack for that.

**Comment by datatypevoid** [comment]
Do you have to use bower specifically? The pack doesn't use bower because it's generally unneeded afaik with npm being available to the entire stack now. I can help you install it if really have to have it, but you'll have to join our Slack for that.

**Comment by datatypevoid** [comment]
Closing this issue for now. Please join our Slack and PM me if you still need help with this.
