### ISSUE TITLE
vulgar exception about permissions when initialize

### ISSUE THREAD

**Issue by ghost** [datatypevoid/vulgar#17]
<img width="605" alt="2016-07-31 11 18 34" src="https://cloud.githubusercontent.com/assets/9084157/17277081/54c287d4-5775-11e6-8d4b-7338a2dc8ce0.png">

I installed vulgar following quick starts https://github.com/datatypevoid/vulgar-cli,
then I got an exception about permission like pictures I upload. (but the project folder was created)
Is it ok? or if it has problem, how can I solve it?
(Although I followed the instruction   chown -R `whoami` ~/.npm    as shown in the picture,
exception doesn't solved)

**Comment by datatypevoid** [comment]
Hey there! This issue should help you out: https://github.com/datatypevoid/vulgar-cli/issues/4

If you still need help feel free to reopen this issue, or join our Slack channel!
