### ISSUE TITLE
Observable Assign Failing

### ISSUE THREAD

**Issue by jnfsmile** [datatypevoid/vulgar#18]
[x] bug report
- **What is the current behavior?**
  When running the console shows the following errors:

```

[default] C:/Users/Naftali/Documents/GitHub/Beshvili4/src/app/recipes/recipe.service.ts:35:5
    Type 'Observable<{}>' is not assignable to type 'Observable<Recipe[]>'.

[default] C:/Users/Naftali/Documents/GitHub/Beshvili4/src/app/recipes/recipes.component.ts:46:5
    Type 'Observable<{}>' is not assignable to type 'Observable<Recipe>'.
```
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.4
- Browser: Chrome 51

**Comment by datatypevoid** [comment]
You've updated the Angular version far beyond what the `master` branch supports. If you want to use the `development` branch, it is on `RC.3` and is actively being brought up to date with the latest releases in these particular spheres of development. Please note that if you choose to use the `development` branch, for the time being, `vulgar-cli` is not compatible until it is refactored to handle the changes brought with the Angular 2 `release candidates`. That being said, there are plenty of us using the `development` branch and actively moving it forward. If you have further questions or are interested in contributing, please join our Slack channel. There is a registration link in the project `README` file.
