### ISSUE TITLE
Webpack Dev Server reloading bug

### ISSUE THREAD

**Issue by lekhmanrus** [datatypevoid/vulgar#21]
- *_I'm submitting a ... *_
  
  [x ] bug report
  
  [ ] feature request
  
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  bug
- **What is the current behavior?**

Webpack Dev Server doesn't reload on changes
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co, https://codepen.io, or similar.

``` bash
$ vulgar init <nameOfApplication>
$ npm start
```
- **What is the expected behavior?**

Browser page reloading on code changes.
- **What is the motivation / use case for changing the behavior?**

Improvement of development process and bug fixes:
![capture](https://cloud.githubusercontent.com/assets/2744696/17719653/f11d68ea-6424-11e6-9a0e-4ee0d8b220fc.JPG)
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.1
- Browser: Chrome 54.0.2824.0 dev-m (64-bit)
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Should be:

``` html
<script src="<%= webpackConfig.metadata.protocol %>://<%= webpackConfig.metadata.host %>:<%= webpackConfig.metadata.port %>/webpack-dev-server.js"></script>
```

on line [index.html:58](https://github.com/datatypevoid/vulgar/blob/master/src/index.html#L58)

**Comment by datatypevoid** [comment]
Hey there, thanks for bringing this to our attention. I appreciate the pull request.

**Comment by datatypevoid** [comment]
I am closing this for the time being as I believe the bug is fixed on the development branch. Will confirm once everything is brought up to speed with the latest and greatest.
