### ISSUE TITLE
Update to RC5

### ISSUE THREAD

**Issue by piotte13** [datatypevoid/vulgar#23]
- *_I'm submitting a ... *_
  
  [ ] bug report
  
  [x ] feature request
  
  [ ] question about the decisions made in the repository

Please update angular2 to support RC5.

**Comment by datatypevoid** [comment]
I am in the process of updating everything to the latest and greatest. The development branch is already quite a bit further along than the master branch if you haven't checked it out.  For more information, please join the vulgar slack: http://www.davidniciforovic.com/wp-login.php?action=slack-invitation
