### ISSUE TITLE
Will vulgar be updated?

### ISSUE THREAD

**Issue by elton-lau** [datatypevoid/vulgar#26]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)
- *_I'm submitting a ... *_
  
  [ ] bug report
  
  [X] feature request
  
  [ ] question about the decisions made in the repository

Will this be updated since the final released version of ng2 has been published?

**Comment by datatypevoid** [comment]
I am now in the process of bringing everything up to speed with the latest and greatest. For more information, please join the vulgar slack: http://www.davidniciforovic.com/wp-login.php?action=slack-invitation
