### ISSUE TITLE
Update  angular 2.0.0-rc.1  to angular 2.0.0

### ISSUE THREAD

**Issue by itranga** [datatypevoid/vulgar#27]
Can we update angular 2.0.0-rc.1  to angular 2.0.0 ?

Thanks

**Comment by datatypevoid** [comment]
After a hectic couple of months at work and Angular 2.0.0 finally releasing, I have finally started the process of bringing everything up to date with the current state of things. The development branch is already quite a bit further along than master, but everything should move along pretty quickly over the next week or so. Wish me luck.

**Comment by jimmythesaint82** [comment]
Good luck :D
