### ISSUE TITLE
Heroku push issue 

### ISSUE THREAD

**Issue by itranga** [datatypevoid/vulgar#29]
I try to push my code to Heroku . I got the following issue .

Output 
................................................
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:  
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  >= 4.2.1
remote:        engines.npm (package.json):   >= 3
remote:  
remote:        Resolving node version >= 4.2.1 via semver.io...
remote:        Downloading and installing node 5.11.1...
remote:        Resolving npm version >= 3 via semver.io...
remote:        Downloading and installing npm 3.10.8 (replacing version 3.8.6)...
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:  
remote:        > vulgar@2.0.4 postinstall /tmp/build_5710146d9436159b3d731c637972749c
remote:        > npm run typings -- install
remote:  
remote:  
remote:        > vulgar@2.0.4 typings /tmp/build_5710146d9436159b3d731c637972749c
remote:        > typings "install"
remote:  
remote:        sh: 1: typings: not found
remote:  
remote:        npm ERR! Linux 3.13.0-95-generic
remote:        npm ERR! argv "/tmp/build_5710146d9436159b3d731c637972749c/.heroku/node/bin/node" "/tmp/build_5710146d9436159b3d731c637972749c/.heroku/node/bin/npm" "run" "typings" "--" "install"
remote:        npm ERR! node v5.11.1
remote:        npm ERR! npm  v3.10.8
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! vulgar@2.0.4 typings: `typings "install"`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the vulgar@2.0.4 typings script 'typings "install"'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the vulgar package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     typings "install"
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs vulgar
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls vulgar
remote:        npm ERR! There is likely additional logging output above.
remote:  
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_5710146d9436159b3d731c637972749c/npm-debug.log
remote:  
remote:        npm ERR! Linux 3.13.0-95-generic
remote:        npm ERR! argv "/tmp/build_5710146d9436159b3d731c637972749c/.heroku/node/bin/node" "/tmp/build_5710146d9436159b3d731c637972749c/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_5710146d9436159b3d731c637972749c/.npmrc"
remote:        npm ERR! node v5.11.1
remote:        npm ERR! npm  v3.10.8
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! vulgar@2.0.4 postinstall: `npm run typings -- install`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the vulgar@2.0.4 postinstall script 'npm run typings -- install'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the vulgar package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     npm run typings -- install
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs vulgar
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls vulgar
remote:        npm ERR! There is likely additional logging output above.
remote:  
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_5710146d9436159b3d731c637972749c/npm-debug.log
remote: 
remote: -----> Build failed
remote:  
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:  
remote:        Some possible problems:
remote:  
remote:        - Dangerous semver range (>) in engines.node
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:  
remote:        Love,
remote:        Heroku
remote:  
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !   Push rejected to apidata.
remote: 
To https://git.heroku.com/apidata.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/apidata.git'

...................................................................
My Procfile

web: node server.js

Thanks

**Comment by datatypevoid** [comment]
Looks like you need to install `typings` based on the line

`remote: sh: 1: typings: not found`

Let me know if this fixes it for you.

**Comment by rschellius** [comment]
Had the same problem. What worked for me is to change the postinstall line in package.json to 

`"postinstall": "npm install typings",`

**Comment by itranga** [comment]
Thanks rschellius . It's working now .

**Comment by datatypevoid** [comment]
Since this is already taken care of in the `development` branch, I'll close this issue.

**Comment by ibarrajo** [comment]
I just ran into this recently.

It was failing in Heroku because the `typings` binary could not be found properly.

I added a new gulp task

```js

gulp.task('installTypings', function() {
  let gulpTypings = require('gulp-typings');
  return gulp.src('./typings.json')
    .pipe(gulpTypings());
});
```

and changed my `postinstall` in package.json to

```json
"postinstall": "gulp installTypings"
```
