### ISSUE TITLE
Hi ! update package Json

### ISSUE THREAD

**Issue by alan345** [datatypevoid/vulgar#30]
Hi, 

It is a very useful  stack.
Do you think you will update it to new angular decencies ? 
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
..

Thanks again !

**Comment by datatypevoid** [comment]
The `development` branch is currently on the latest Angular and Webpack ;)

**Comment by alan345** [comment]
Thanks!!
