### ISSUE TITLE
How about upgrading to the final release of Angular 2?

### ISSUE THREAD

**Issue by joelmheim** [datatypevoid/vulgar#31]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)

- **I'm submitting a ... **

  [ ] bug report

  [X ] feature request

  [ ] question about the decisions made in the repository

- **Do you want to request a _feature_ or report a _bug_?**
- **What is the current behavior?**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- <https://plnkr.co>, <https://codepen.io>, or similar.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Some of the other dependencies can be updated too I think. But changes in the Angular core (and probably router) makes it difficult to do just by updating the version numbers in the package.json.

I will try to get a pull request together on this, so that you don't have to do all the work. We have some experience from a project at work which I can try to leverage.

**Comment by datatypevoid** [comment]
Hey there @joelmheim ! While your offer is more then generous and I do greatly appreciate it, the [development](https://github.com/datatypevoid/vulgar/tree/development) branch has been brought up to date with the latest in the `Angular 2` release (currently `2.1.x` I believe) as well as `Webpack 2`. That being said, there is still some work to be done such as a complete facelift seeing as I ripped out `Angular 2 Material` as well as an overhaul of the `CLI` and generators. If you are interested in collaborating, please feel free to join our project `Slack` channel [here](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation).
