### ISSUE TITLE
/src/app/app.ts

### ISSUE THREAD

**Issue by kreviceko** [datatypevoid/vulgar#34]
File /src/app/app.ts is not located in the repository.

**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)

- **I'm submitting a ... **

  [X ] bug report

  [ ] feature request

  [ ] question about the decisions made in the repository

- **Do you want to request a _feature_ or report a _bug_?**
- **What is the current behavior?**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- <https://plnkr.co>, <https://codepen.io>, or similar.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by datatypevoid** [comment]
Depending on what you are looking for, it is most certainly there. You didn't give me much information to work with, but here is the `Master` version of `app.component.ts`: https://github.com/datatypevoid/vulgar/blob/master/src/app/app.component.ts

That's the top level app component.

For the record, consider using `Development` if you aren't already, it is much further along. Be warned that neither the accompanying Todo tutorial or the vulgar-cli will work with the `Development` branch.
