### ISSUE TITLE
after init and npm install, npm run build errors

### ISSUE THREAD

**Issue by cmwhited1990** [datatypevoid/vulgar#4]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)

- **I'm submitting a ... **

[npm-debug-log.txt](https://github.com/datatypevoid/vulgar/files/217514/npm-debug-log.txt)
![vulgar cli snapshot](https://cloud.githubusercontent.com/assets/15879449/14501342/68c854d0-016b-11e6-8210-f8d21f786878.PNG)

  [X ] bug report

  [ ] feature request

  [ ] question about the decisions made in the repository

Following along with the vulgar-cli quick start. 
-Ran the npm install -g vulgar-cli generator-vulgar.
-Ran vulgar init <appName>
-cd <appName>
-npm install
-npm run build --> THIS THROWS ERROR
   -- Error starts at "Cannot find module './config.json'
   -- Please see included image and npm debug log

ENVIRONMENT:
-node.js version 5.10.1
-npm version 3.8.6
-Windows 7 x64

**Comment by datatypevoid** [comment]
Hmm, I will have to take a look. As far as I know it should run fine. Can you check to see if it generated `config/config.json`?

**Comment by cmwhited1990** [comment]
it did not generate config/config.json

**Comment by datatypevoid** [comment]
I'll take a look later when I get off of work. I'll let you know what I uncover!

**Comment by cmwhited1990** [comment]
Thanks. I appreciate it.

**Comment by datatypevoid** [comment]
No problem. If you want to try and get around this for now, you can insert this object into config/config.json and run `vulgar init` again: 

```
{
  "ENV" : "development",
  "PORT" : 3000,
  "MONGO_URI" : {
    "DEVELOPMENT" : "mongodb://localhost:27017/vulgar-dev",
    "PRODUCTION" : "mongodb://localhost:27017/vulgar-prod",
    "TEST" : "mongodb://localhost:27017/vulgar-test"
  },
  "SESSION_SECRET" : "355FC4FE9348639B4E4FED1B8E93C"
}
```

That should bypass that error hopefully.

**Comment by datatypevoid** [comment]
Standard installation works fine for me on multiple Win10 x64 boxes as well as a Ubuntu 14.04 box. Have you had any progress on your end?
